# Generated by Django 4.1.7 on 2023-02-14 19:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restuarants',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('direction', models.CharField(max_length=120, verbose_name='Direction')),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='name')),
                ('ype', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('COFFEE', 'Coffee'), ('DINNER', 'Dinner')], max_length=20)),
                ('thumbnail', models.ImageField(default='recipe_thumbnail/default.png', upload_to='recipe_thumbnails')),
                ('restuarant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restuarants')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('recipe', models.ManyToManyField(to='api.recipe')),
            ],
        ),
    ]
