# Generated by Django 4.1.7 on 2023-02-14 22:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.RenameModel(
            old_name='Restuarants',
            new_name='Restaurant',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='restuarant',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ype',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(default='recipe_thumbnails/default.png', upload_to='recipe_thumbnails'),
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ManyToManyField(to='api.recipe'),
        ),
    ]
